language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  app: warm-everglades-53164
  on:
    repo: denriquem/acebook--TeamFavouriteFreindLove-
  run:
    - bundle exec rails db:create
    - bundle exec rails db:migrate
  api_key:
    secure: XeNHFuWU4HeYOXitNqVapJKBfZaAx4cbOSK9Ak0/ZlTuaiAwmTX1bklMjULt7poEbIq3vYq533hOi+wfdQBzHXDkxTPp/GfpJlB5IB2ynXzO0tgxM/c03J46Ngn6TIyrma/t7wWF9E33GR14pXTPhFiVVhl3OYYQwwHzZY332W7AUBIVHw1QJWWxva7T6fq7pBBTSaME+s40x+61CgW1jUQ6tabkMTjRf6QeeITBDqOTBA8/BX2ou3IxYNW97EK0Zrd6lYJlozRzwSm0NdfnUtUHgAbXLwULfAoIRRaqwEAxPka2msmWSptv2+bKjnqnVnl4P+uCr99Dx1WGTgQQ43x8uNWPm6nrAdBYvNKCVmrpmfqxVhEbY3Ij5HxFSfp2MOLKIQWlhsU0/pDlL24b8+BEwI5gCV8cdNjRjn9qeuxhZywA7qbNQl+e3k4qlSfZyD+VLT37OSM9mCjSckhckBtKsf7qTvcPlawoo+hMEb7odxE9rNEnet4nfQkH7s38lYpfy8qfnhEIAYhREiXdqnzggKLie9/wv6ZD0sYAIGuN6nBms4BT6HQYqlpORBd//HWSkYaeLcMvxDraGc/HM+zP05mc59Ds1hmPUE6vYfpn1+yfWO4aq6ldfSPQT83pkeQA96v7j8zzo1390xAIsiPnMlFy/L5Ip3yVY0mM6xE=
