language: ruby
rvm:
  - 2.6.3
services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=59c9ecfc93beafa930ea8169ace46ecb771db3d298e08602179b62c0fdb4f177

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

deploy:
  provider: heroku
  api_key:
    secure: l0HmSf2sT6VcufkChrqO511hjrM8lT7lWMcYEIGOQEBkBx7M7ZOn2VNbNssGb6BF71mkxRbHSQm64SZTNt4zk7KpL1y0pIiAlQOLDZOj2qruwx80RMGQr84Kph39uHb3zqUZireJrs
GRRA/fUvuXCJlSlUIkjpwrOI2h366v9Bo24cYOukdovl1J+zzZV7i5nD9ii4d//QsbWHiJcWOXmh0IqaA1WkYpQLxTN/2UtRMglNB3H9qAJQIvUflSPO2ouUyGFZIvPz0DssBOKHCxgWL+TBR01jx
wkj1LX+7PvG1tyrwP6AzNUZKB6TJGxm2qah9T05rgA5GnSGALAyvfI3lRifADAZyJ36DkedfsfjZOYPbg2r05LYlNgNh0ZMe4L1cQ9LtoWSSKwU7Wi3jlwliw9qHMGvAjATBTGyNjUK+mDJf4xFwn
Xp6fwna6XdIbXDc68TZssC5xfPD8NQUv9EMuNcv4XGGsS2sMoGeBbiLLV9W4mR7g5JEGs3m5S6uT1DttqeLJgGapEj7djvMANqwmbwSZQBPxfjslvAs/BZwo/XACQgpjCTm2ttjGEkmrSM78wI1Cz
lo1OGE/ZFGuo7TRMdq5fQqy17HqDGsoyWGYl2OcrkapZd2yV5FEoOrK2iJx6irWaXvfX3+PSo6za2v1aynsQVenedFia66Gpe4=
    app: warm-everglades-53164
    on:
      repo: denriquem/acebook--TeamFavouriteFreindLove-

script:
  - bundle exec rspec
  - bundle exec rubocop

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
