dist: bionic

language: ruby

rvm:
  -2.5.0
  
services:
  -postgresql
  -xvfb

env:
  global:
    -MOZ_HEADLESS=1

addons:
  firefox: latest

sudo: required

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
  - sudo cp geckodriver /usr/bin
  - bin/rails db:create
  - bin/rails db:migrate

script:
  -xvfb-run -a bundle rspec
  -bundle exec rubocop -c .rubocop.yml .
